### ISSUE TITLE
TypeError: Cannot call method 'read' of undefined

### ISSUE THREAD

**Issue by mikoim** [sandeepmistry/node-sensortag#28]
I ran test.js on follow environment and got 'TypeError: Cannot call method 'read' of undefined'.

OS X Yosemite 10.10.1
sensortag 0.1.9
noble 0.3.6

```
Mac:sensortag name$ node test.js
connect
discoverServicesAndCharacteristics
readDeviceName

/Users/name/node_modules/sensortag/index.js:174
  this._characteristics[uuid].read(function(error, data) {
                              ^
TypeError: Cannot call method 'read' of undefined
    at SensorTag.readDataCharacteristic (/Users/name/node_modules/sensortag/index.js:174:31)
    at SensorTag.readStringCharacteristic (/Users/name/node_modules/sensortag/index.js:180:8)
    at SensorTag.readDeviceName (/Users/name/node_modules/sensortag/index.js:186:8)
    at /Users/name/node_modules/sensortag/test.js:25:19
    at /Users/name/node_modules/async/lib/async.js:610:21
    at /Users/name/node_modules/async/lib/async.js:249:17
    at iterate (/Users/name/node_modules/async/lib/async.js:149:13)
    at /Users/name/node_modules/async/lib/async.js:160:25
    at /Users/name/node_modules/async/lib/async.js:251:21
    at /Users/name/node_modules/async/lib/async.js:615:34
```

**Comment by sandeepmistry** [comment]
This is fixed in master, ```readDeviceName``` now passes an error parameter on the callback
